---
title: "MetData"
output: html_document
date: "2025-02-18"
---



```{r}
library(tidyverse)
library(dplyr)
library(raster)
library(rgdal)
library(rgeos)
library(mapview)
library(sf)
library(sp)
library(maps)
library(leaflet)
library(randomcoloR)
library(wesanderson)
library(leaflegend)
library(osmdata)
library(MetBrewer)
library(colorBlindness)
library(colorblindcheck)
library(ggmap)
library(maptools)
library(spatstat)
library(elevatr)
library(gdalUtils)
library(rgdal)
library(terra)


getwd()
# "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/BatLab Norway/GitHubLink/NocturBats"

## Setup output directory 

output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/BatLab Norway/GitHubLink/CoastalMonitoring/Outputs"

file.name <- "MetData"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today

#"C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/BatLab Norway/GitHubLink/CoastalMonitoring/Outputs/MetData_2025-02-18"

```

https://github.com/metno/NWPdocs/wiki/Examples
https://github.com/metno/NWPdocs/wiki/MET-Nordic-dataset 

```{r}


```

