---
title: "Sara_BasicOverview_CombineManualIDs"
output: html_document
date: "2025-02-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(dplyr)
library(beepr)
library(lubridate)
library(purrr)
library(janitor)
library(renv)
library(stringr)
library(beepr)
library(MetBrewer)
library(randomcoloR)
library(wesanderson)
library(osmdata)
library(MetBrewer)
library(colorBlindness)
library(colorblindcheck)
library(MoMAColors)


getwd()
# "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/BatLab Norway/GitHubLink/NocturBats"

## Setup output directory 

output <- "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/BatLab Norway/GitHubLink/CoastalMonitoring/Outputs"

file.name <- "Sara_BasicOverview_CombineManualIDs"

todays_date <- Sys.Date()
 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
dir.name
 
output_today <- dir.name
output_today

dir.create(output_today)
output_today

#"C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/BatLab Norway/GitHubLink/CoastalMonitoring/Outputs/Sara_BasicOverview_CombineManualIDs_2025-02-24"

```



```{r}

## Read in the processed data

# CM-18
inputCM18 <- read_csv("P:/SW_CoastalMonitoring/Data_analysis_2024/MSc_Theses/Sara/ID/CM-18/id.csv") 
# 491 obs of 44 vars
# Add a site column 
inputCM18$site <- "CM-18"

# CM-19
inputCM19 <- read_csv("P:/SW_CoastalMonitoring/Data_analysis_2024/MSc_Theses/Sara/ID/CM-19/id.csv") 
# 1262 obs of 44 vars
# Add a site column 
inputCM19$site <- "CM-19"

# CM-20
inputCM20 <- read_csv("P:/SW_CoastalMonitoring/Data_analysis_2024/MSc_Theses/Sara/ID/CM-20/id.csv") 
# 972 obs of 44 vars
# Add a site column 
inputCM20$site <- "CM-20"

# CM-22
inputCM22 <- read_csv("P:/SW_CoastalMonitoring/Data_analysis_2024/MSc_Theses/Sara/ID/CM-22/id.csv")
# 5445 obs of 44 vars
# Add a site column 
inputCM22$site <- "CM-22"

# CM-26
inputCM26 <- read_csv("P:/SW_CoastalMonitoring/Data_analysis_2024/MSc_Theses/Sara/ID/CM-26/id.csv") 
# 3089 obs of 44 vars
# Add a site column 
inputCM26$site <- "CM-26"

# CM-28
inputCM28 <- read_csv("P:/SW_CoastalMonitoring/Data_analysis_2024/MSc_Theses/Sara/ID/CM-28/id.csv")
# 5231 obs of 44 vars
# Add a site column 
inputCM28$site <- "CM-28"

# CM-39
inputCM39 <- read_csv("P:/SW_CoastalMonitoring/Data_analysis_2024/MSc_Theses/Sara/ID/CM-39/id.csv") 
# 306 obs of 44 vars
# Add a site column 
inputCM39$site <- "CM-39"

inputCM40 <- read_csv("P:/SW_CoastalMonitoring/Data_analysis_2024/MSc_Theses/Sara/ID/CM-40/id.csv")
# 1111 obs of 44 vars
# Add a site column 
inputCM40$site <- "CM-40"

# CM-49 
inputCM49 <- read_csv("P:/SW_CoastalMonitoring/Data_analysis_2024/MSc_Theses/Sara/ID/CM-49/id.csv") 
# 2194 obs of 44 vars
# Add a site column 
inputCM49$site <- "CM-49"

## QUALITY CONTROL CHECK 

# Fix the Manual ID and AUTO ID name columns 
inputCM18 <- inputCM18 %>% rename("MANUAL ID" = "MANUAL ID*")
inputCM19 <- inputCM19 %>% rename("MANUAL ID" = "MANUAL ID*") 
inputCM20 <- inputCM20 %>% rename("MANUAL ID" = "MANUAL ID*") 
inputCM22 <- inputCM22 %>% rename("AUTO ID" = "AUTO ID*") 
inputCM26 <- inputCM26 %>% rename("MANUAL ID" = "MANUAL ID*") 
inputCM28 <- inputCM28 %>% rename("MANUAL ID" = "MANUAL ID*") 
inputCM39 <- inputCM39 %>% rename("MANUAL ID" = "MANUAL ID*")
inputCM40 <- inputCM40 %>% rename("MANUAL ID" = "MANUAL ID*")
inputCM49 <- inputCM49 %>% rename("MANUAL ID" = "MANUAL ID*")
# Does every input file for each site correspond to only ONE detector? check serial number in the file names
## Manually checked - looks good! 

cm <- bind_rows(inputCM18, inputCM19, inputCM20,
                inputCM22, inputCM26, inputCM28, 
                inputCM39, inputCM40, inputCM49)  

491 + 1262 + 972 + 
5445 + 3089 + 5231 + 
306 + 1111  + 2194 

dim(cm)
# 20101    45
names(cm)

summary(cm) # No weird/obvious NAs 
# write.csv(cm, file = file.path(output_today, "AllSaraSites_ManualID.csv")) 
# 24.02.2025

```




```{r}
df1 <- cm %>% 
  rename(
  filename = "IN FILE",
  autoid = "AUTO ID",
  manualid = "MANUAL ID",
  DATE.12 = 'DATE-12',
  HOUR.12 = 'HOUR-12',
  TIME.12 = 'TIME-12') %>% 
  mutate(autoid = factor(autoid), 
         manualid = factor(manualid), 
         site = factor(site)) %>% 
  dplyr::select(filename, DURATION, 
                DATE, TIME, HOUR,
                DATE.12, TIME.12, HOUR.12,
                autoid, manualid, site
                )

levels(df1$manualid)

### Something a bit strange happened with the PNAT.T observations later in this workflow. I am going to create a reference to the original manual.ids to check this later... I fixed the original issue but I will leave this code here in case a ref object is useful in future workflows. 

# ref <- df1 %>% select(filename, manualid) 

### Check for duplicates!
test <- df1 %>% 
  group_by(filename) %>% 
  summarise(n = n()) %>% 
  filter(n > 1) %>% 
  arrange(desc(n))
# No duplicates, that is cool.

levels(df1$manualid)  

## simple fix first - noise is noise is noise 
df1.5 <- df1 %>% mutate(
  mid = factor(case_when(
         str_detect(manualid, "Noise") ~ "Noise", 
                            TRUE  ~ manualid))) %>% 
  dplyr::select(-manualid) %>% 
  rename(manualid = mid) 

levels(df1.5$manualid)  

## Parse out multiple bat passes
mcols <- c("manual_pass1", "manual_pass2", "manual_pass3")

df2 <- df1.5 %>% 
  tidyr::separate( col = manualid,
                   sep = "_", 
                   into = mcols)


# Only the second bat taxa found in a pass 
bat2 <- df2 %>% select(manual_pass2, filename) %>% drop_na() %>% 
  rename(manual_pass = manual_pass2) %>% mutate(manual_pass = factor(manual_pass)) 
dim(bat2) # 303   2
# 2199 obs with 2 bats 

## Only the third bat taxa found in a pass 
bat3 <- df2 %>% select(manual_pass3, filename) %>% drop_na() %>%
  rename(manual_pass = manual_pass3) %>% mutate(manual_pass = factor(manual_pass))
dim(bat3)
# 77 obs with 3 bats

# remove these columns from df1 
mdf2 <- df2 %>% select(-c(manual_pass2, manual_pass3)) %>% 
               rename(manual_pass = manual_pass1) %>% mutate(manual_pass = factor(manual_pass)) # 15470 obs

blist <- bat2$filename # meta data for all bat passes which had multiple bats 

## re-attach the meta data  missing for the files of second and third bat observations
timemap <- df2 %>% 
  select(filename, 
                          DATE, TIME, HOUR,
                          DATE.12, TIME.12, HOUR.12,
                          autoid, site) %>% 
  distinct() %>% filter(filename %in% blist) 




bats2 <- left_join(bat2, timemap)
bats3 <- left_join(bat3, timemap)

# 20101 + 2199 + 77 = 22377
mdf3 <- full_join(mdf2, bats2) # 22300 obs - that adds up, good!  
mdf4 <- full_join(mdf3, bats3) # 22377 obs - good! 
# 20101 + 2199 + 77 = 22377- great!

levels(mdf4$manual_pass)

# Now behavior 
df5 <- mdf4 %>%
  mutate(manualid = as.character(manual_pass)) %>% 
  mutate(behavior = case_when(
    manualid == "Noise" ~ "Noise",
    str_detect(manualid,"\\.T\\.B") ~ "Feeding",
    str_detect(manualid,"\\.T\\.S\\.B") ~ "Feeding",
    str_detect(manualid, "\\.B") ~ "Feeding",
    str_detect(manualid, "\\.S") ~ "Social",
    str_detect(manualid, "\\.T\\.S") ~ "Terretorial",
    str_detect(manualid, "\\.T") ~ "Terretorial",
    TRUE ~ "Commuting"
  )) %>% 
  mutate( behavior= factor(behavior),
          manualid = factor(manualid)) 

summary(df5$behavior)
  # Commuting     Feeding       Noise      Social Terretorial 
  #     15289        1334        4206         421        1127 


summary(df5$manualid)
## Now remove the behavior tags from the manual acoustic analysis column 

df5$mid <- factor(gsub("\\.B", "", df5$manualid)) 
summary(df5$mid)

df5$mid1 <- factor(gsub("\\.S", "", df5$mid)) 
summary(df5$mid1)

df5$mid2 <- factor(gsub("\\.T", "", df5$mid1)) 
summary(df5$mid2)

df5$mid3 <- factor(gsub("NNOC.NY", "NYCT", df5$mid2))
summary(df5$mid3)

df5$mid4 <- factor(gsub("NYCTCT", "NYCT", df5$mid3))
summary(df5$mid4)

df5$mid5 <- factor(gsub("PPYG.", "PPYG", df5$mid4)) 
summary(df5$mid5)

# ENIL  MYOT  NNOC  NYCT  NoID Noise  PAUR  PISP  PNAT  PPYG  VMUR 
#  3982   732   517  3260    56  4206    68    43  2902  6608     3

## Some small issues to remedy here with how the gsub function was interpretted 
df7 <- df5 %>% 
  mutate(manual.id = mid5) %>% 
  dplyr::select(-c(
  manual_pass, manualid, mid, mid1, mid2, mid3, mid4, mid5))
  
names(df7)

summary(df7$manual.id)
 # ENIL  MYOT  NNOC  NYCT  NoID Noise  PAUR  PISP  PNAT  PPYG  VMUR 
 # 3982   732   517  3260    56  4206    68    43  2902  6608     3 

#Nice! 
# All clean! 

# Add a more informative bat taxa column 
DF <- df7 %>% mutate(taxa = factor(case_when(
  manual.id == "PAUR" ~ "Brown long-eared bat",
  manual.id == "MYOT" ~ "Myotis species",
  manual.id == "PNAT" ~ "Pipistrellus nathusii",
  manual.id == "PPYG" ~ "Pipistrellus pygmaeus",
  manual.id == "PISP" ~ "Pipistrellus species",
  manual.id == "ENIL" ~ "Eptesicus nilssonii", 
  manual.id == "NYCT" ~ "Nyctaloid",
  manual.id == "NNOC" ~ "Nyctalus noctula",
  manual.id == "VMUR" ~ "Vespertilio murinus",
  manual.id == "NoID" ~ "Unknown bat", 
  manual.id == "Noise" ~ "Not a bat", 
)))  
levels(DF$taxa)
summary(DF$taxa)
summary(DF)
dim(DF)
# 22377 obs of 13 vars

# write.csv(DF, file = file.path(output_today, "Sara_ManualAcousticAnalysis_Cleaned_MissingFilesNotIncluded.csv")) 
# # 25.02.2025


```



## Visualize and explore - just to help you get started
```{r}

## Look at overall recording period 
ggplot(DF) + 
  geom_point(aes(x = DATE.12, y = site), 
             color = "orange", alpha = 0.5, size = 3) +
    xlab("Date in season") + ylab(" ") +
  ggtitle("Recording activity") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"))

# ggsave(path = output_today, filename = "BasicRecordingOverview.tiff", width = 23, height = 14, device='tiff', dpi=300) 


## Now just look at PNAT
ggplot(DF %>% filter(manual.id == "PNAT") %>% droplevels())  + 
  geom_point(aes(x = DATE.12, y = site), 
             color = "#D02E55", alpha = 0.5, size = 3) +
    xlab("Date in season") + ylab(" ") +
  ggtitle("Recording activity - Trolls") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"))
# ggsave(path = output_today, filename = "PNAT_BasicRecordingOverview.tiff", width = 23, height = 14, device='tiff', dpi=300) 



## Now just look at target taxa / behaviors
ggplot(DF %>% filter(manual.id == "NNOC") %>% droplevels())  + 
  geom_point(aes(x = DATE.12, y = site), 
             color = "brown", alpha = 0.5, size = 3) +
    xlab("Date in season") + ylab(" ") +
  ggtitle("Recording activity - Stor") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"))


ggplot(DF %>% filter(manual.id == "NYCT") %>% droplevels())  + 
  geom_point(aes(x = DATE.12, y = site), 
             color = "black", alpha = 0.5, size = 3) +
    xlab("Date in season") + ylab(" ") +
  ggtitle("Recording activity - Nyctaloids") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"))


ggplot(DF %>% filter(manual.id == "VMUR") %>% droplevels())  + 
  geom_point(aes(x = DATE.12, y = site), 
             color = "pink", alpha = 0.5, size = 3) +
    xlab("Date in season") + ylab(" ") +
  ggtitle("Recording activity - VMUR") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"))


## Something strange here... 
ggplot(DF %>% 
         filter(manual.id == "PNAT") %>%
         filter(behavior == "Terretorial") %>%
         droplevels())  + 
  geom_point(aes(x = DATE.12, y = site), 
             color = "pink", alpha = 0.8, size = 3) +
    xlab("Date in season") + ylab(" ") +
  ggtitle("Recording activity - sexy pips") + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"))


## Make a figure illustrating proportion of different taxa for each sites 
barnoise <- ggplot(DF) + 
  geom_bar(aes(x= site, fill = manual.id), position = "fill") +
  scale_fill_manual(name = "Taxa", values = moma.colors("Warhol", n = 11)) + 
  ylab("Proportion of recordings") + 
  xlab("Site") +
  theme(text = element_text(size = 25)) 
barnoise



```

## Figures of Obrestad Fyr for communicating with the landowners/getting access
```{r}

bats <- read_csv("C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/BatLab Norway/GitHubLink/CoastalMonitoring/Outputs/Sara_BasicOverview_CombineManualIDs_2025-02-25/Sara_ManualAcousticAnalysis_Cleaned_MissingFilesNotIncluded.csv",col_select = -1)
names(bats)
ob <- bats %>% 
  filter(site == "CM-28") %>% 
  mutate(behavior = factor(behavior), 
         site = factor(site), 
         taxa = factor(taxa), 
         manual.id = factor(manual.id), 
         autoid = factor(autoid)) 
summary(ob)  
dim(ob)
# 5915  

bats$site <- factor(bats$site)
levels(bats$site)

ob1 <- ob %>% filter(manual.id != "Noise") %>% droplevels()


summary(ob$manual.id)
 # ENIL  NNOC  NYCT  NoID Noise  PAUR  PISP  PNAT  PPYG  VMUR 
 #  343     8   586    15   473     2    20  1420  3047     1 
  
summary(ob$autoid) 
# BARBAR NYCNOC   NoID  Noise PIPNAT PIPPYG PLEAUR 
#    108    181   1237      5   1417   2946     21 

barnoise <- ggplot(ob1, aes(x= taxa, fill = taxa)) + 
  stat_count(geom = "bar", size= 4, alpha = 0.90) +
  scale_fill_manual(name = "Taxa", values = moma.colors("Warhol", n = 10)) + 
  ylab("Number of recordings") + 
  xlab("") +
  theme_minimal(base_size = 15)
barnoise





ggplot(ob1, aes(x= DATE.12, color = taxa)) +
          stat_count( geom = "point", size= 4, alpha = 0.90) +
   scale_color_manual(name = "Taxa", values = moma.colors("Warhol", n = 10)) +
   ylab("Bat passes per night") + xlab("Night in season") +
   theme_minimal(base_size = 20) 

ggplot(ob1, aes(x= DATE.12))  + 
  stat_count(geom = "point", size= 4, alpha = 0.90, color = "#D02E55") +
     ylab("Bat passes per night") + xlab("Night in season") +
   theme_minimal(base_size = 20) 


ggplot(ob %>% filter(manual.id %in% c("PNAT", "NYCT", "NNOC", "VMUR")) %>% droplevels(), aes(x= DATE.12, color = taxa)) +
          stat_count( geom = "point", size= 4, alpha = 0.90) +
   scale_color_manual(name = "Taxa", values = c("#D1AAC2", "#A44F6C", "#3FA750", "#FBA603")) +
  facet_wrap(~taxa, nrow=5) + 
   ylab("Bat passes per night") + xlab("Night in season") +
  ggtitle("Species capable of long distance migration") +
   theme_minimal(base_size = 20) 

ggplot(ob %>% filter(manual.id == "PNAT") %>% droplevels(), 
aes(x= DATE.12, color = taxa)) +
          stat_count( geom = "point", size= 4, alpha = 0.90, color = "#3FA750") +
   ylab("Bat passes per night") + xlab("Night in season") +
  ggtitle("Trollflaggermus") +
   theme_minimal(base_size = 20) 


## Also Orrefriluftshus 

or <- bats %>% 
  filter(site == "CM-26") %>% 
  mutate(behavior = factor(behavior), 
         site = factor(site), 
         taxa = factor(taxa), 
         manual.id = factor(manual.id), 
         autoid = factor(autoid)) 
summary(or)  
dim(or)
# 3367        

or1 <- or %>% filter(manual.id != "Noise") %>% droplevels()


summary(or1$manual.id)
# ENIL NNOC NYCT NoID PAUR PISP PNAT PPYG VMUR 
#  725  140 1256   11   56    2  244  282    2             

```

